//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthbridgeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthBridgeDBEntities : DbContext
    {
        public HealthBridgeDBEntities()
            : base("name=HealthBridgeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Invoice> tb_Invoice { get; set; }
        public virtual DbSet<tb_Invoice_Line> tb_Invoice_Line { get; set; }
        public virtual DbSet<tb_Patient> tb_Patient { get; set; }
    }
}
